### ISSUE TITLE
Add a CSS-based fallback for IE8 and IE9

### ISSUE THREAD

**Issue by coliff** [Rundiz/bootstrap-basic4#13]
Bootstrap 4 drops support for IE8 and IE9, and although usage of these old browsers is very small, it'd still be good to add a fallback CSS file via a conditional statement.
I maintain an open-source solution which could be used: https://github.com/coliff/bootstrap-ie8
I've tested it with the bootstrap-basic4 theme in a Virtual Machine with IE8 and it works quite well and fixes many layout issues.

**Comment by ve3** [comment]
Sorry, but I think we should drop these versions of IE as Bootstrap 4 drop support for them and to make it simple, basic (as name).

**Comment by coliff** [comment]
ok, no problem. Maybe we should add a note to the Readme noting that IE8/IE9 is not supported,
