### ISSUE TITLE
404 error in child theme on main.js

### ISSUE THREAD

**Issue by scorp13** [Rundiz/bootstrap-basic4#25]
**File: bootstrap-basic4\inc\classes\BootstrapBasic4.php**

Using get_stylesheet_directory_uri() in line
`wp_enqueue_script('bootstrap-basic4-main', get_stylesheet_directory_uri() . '/assets/js/main.js', array('jquery'), false, true);`
of enqueueScriptsAndStyles function cause 404 error in child theme. It looks like need to use get_template_directory_uri () instead.

**Comment by ve3** [comment]
https://github.com/Rundiz/bootstrap-basic4/commit/66d99b0e5f9ba33212b14e2621f2c3e4bba83ab3

https://themes.trac.wordpress.org/ticket/58267
