### ISSUE TITLE
Update to Bootstrap v4 Alpha 5

### ISSUE THREAD

**Issue by coliff** [Rundiz/bootstrap-basic4#4]
Update to Bootstrap v4 Alpha 5
REF: http://v4-alpha.getbootstrap.com/getting-started/download/

**Comment by ve3** [comment]
I was downloaded Bootstrap 4 alpha 5 but I'm really confused. There are many css files such as bootstrap-flex, bootstrap-grid, bootstrap-reboot, bootstrap all with .min.css and without .min.css
Which files do I have to use? All of them? There are nothing in the document tell me about this.

**Comment by ve3** [comment]
done

**Comment by coliff** [comment]
Cool - they changed the bundled CSS options... I read about it on the blog: http://blog.getbootstrap.com/2016/10/19/bootstrap-4-alpha-5/
