### ISSUE TITLE
Make page content wider

### ISSUE THREAD

**Issue by kbecker87** [Rundiz/bootstrap-basic4#6]
Hi! Could you help me figure out what I have to change to get a wider content area? I think the way its now ist kind of narrow on big screens. Thanks!

**Comment by coliff** [comment]
Can you share a link to a site showing the issue?

**Comment by ve3** [comment]
https://github.com/Rundiz/bootstrap-basic4/blob/master/functions.php

In your functions.php file, change the values of `$bootstrapbasic4_sidebar_left_size`, `$bootstrapbasic4_sidebar_right_size`.
Summary of all number must not greater than 12 and the main column size will be calculated automatically.

Example: 
```
$bootstrapbasic4_sidebar_left_size = 2;
$bootstrapbasic4_sidebar_right_size = 2;
// main column will be 8 if both sidebars activate.
```

I hope this can be help.

**Comment by kbecker87** [comment]
@coliff Sorry, I’m still using MAMP to try out
@ve3 Thanks, that did the trick 😊
