### ISSUE TITLE
Border, Navigation

### ISSUE THREAD

**Issue by kbecker87** [Rundiz/bootstrap-basic4#7]
Sorry to bother you again but I’m a bit overwhelmed which CSS files I should work on to change some basic looks of my page. For Instance I’ve got a really light border around all elements:

<img width="682" src="https://cloud.githubusercontent.com/assets/8436596/24830918/40a9a626-1c8f-11e7-9ce4-b3025ead996c.png">

Another thing I’d like to do is hiding the top navigation bar – is that possible?

Thanks for your help!

**Comment by ve3** [comment]
To hide top navbar, remove from `<header class="page-header page-header-sitebrand-topbar">` to `</header><!--.page-header-->` in header.php

To override style, use inspector in your browser to get how css selector was called.
Create your css file and enqueue into the theme.
Add those copied css selector into new css file, make change and save.

**Comment by kbecker87** [comment]
perfect, thanks!

**Comment by ve3** [comment]
I'm sorry that I can't write an example code for you because I'm currently don't have WordPress with Bootstrap Basic 4 installed.
