### ISSUE TITLE
Some Bootstrap 4 tools missing. How can I solve this? 

### ISSUE THREAD

**Issue by carpben** [Rundiz/bootstrap-basic4#8]
I''m trying to work with these theme as a basis. 
The 'Bootstrap Basic4 help'  tab in Wordpress admin it says: "This theme can use all Bootstrap 4 classes, elements and styles. Please read the Bootstrap 4 document.". However I tried to use some of Bootstrap's mixins (such as @include media-breakpoint-up(md) ) and define the breakpoints at variables.scss to change the breakpoints, but it seems those files are missing from the theme.

**Comment by ve3** [comment]
I did not include those .scss files but you can make it your child theme or new parent theme and dequeue the bootstrap .css file and use those .scss.
I have no idea how to use .scss with the web page.
